apiVersion: v1
kind: Service
metadata:
  name: web-lb
  labels:
    app: web
spec:

  # 서비스 타입 : LoadBalancer
  type: LoadBalancer

  # 매치할 파드 Label 선택
  selector:
    app: db
    
  # 포트 설정
  ports:
  - port: 8080
    targetPort: 8080